config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#index'

  # get '/index' => 'pages#index'
  # OPEN SINGLE CALC PAGE
  get '/singlecalculation' => 'pages#calc'
  get '/weather' => 'pages#weather'  

  resources :users, :activities

  resources :meals do
    resources :foods
  end

  resources :bloodsugars, only: [:index] do
    collection { post :import }
  end

  # JSON ROUTES
  get '/dashboard' => 'users#dashboard'

  # BLOODSUGAR DATA JSON PAGE
  get '/readingdata' => 'bloodsugars#data'
  get '/readingdata/bslevel' => 'users#bslevel'
  get '/readingdata' => 'bloodsugars#data'
  get '/readingdata/readingtime' => 'users#readingtime'
  get '/readingdata/bslevel_lastthirty' => 'users#bslevel_lastthirty'
  get '/readingdata/readingtime_lastthirty' => 'users#readingtime_lastthirty'
  # MEAL DATA JSON PAGE
  get '/readingdata/foods' => 'foods#index'
  get '/readingdata/carbs' => 'foods#carbs'
  get '/readingdata/mealtime' => 'foods#mealtime'
  get '/readingdata/carbs_lastthirty' => 'foods#carbs_lastthirty'
  get '/readingdata/mealtime_lastthirty' => 'foods#mealtime_lastthirty'
  # ACTIVITY DATA JSON PAGE
  get '/readingdata/duration' => 'activities#duration'
  get '/readingdata/activity_time' => 'activities#activity_time'
  get '/readingdata/duration_lastthirty' => 'activities#duration_lastthirty'
  get '/readingdata/activity_time_lastthirty' => 'activities#activity_time_lastthirty'

  # SESSION LOGIN PAGE
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'


end

app/models/meal.rb
# == Schema Information
#
# Table name: meals
#
#  id          :integer          not null, primary key
#  meal_time   :datetime
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#  total_carbs :float
#  meal_date   :datetime
#

class Meal < ActiveRecord::Base
  belongs_to :user
  has_many :foods
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  before_action :check_if_logged_in, :only => [:index]

  def index
    @meals = @current_user.meals
    sum = 0
  end

  def new
    @meal = Meal.new
  end

  def create
    meal_time = DateTime.parse(meal_params[:meal_date] + ' ' + meal_params[:meal_time])

    meal = @current_user.meals.create({
      user_id: meal_params[:user_id],
      total_carbs: meal_params[:total_carbs],
      meal_time: meal_time
    })
    redirect_to meal
  end

  def show
    @meal = Meal.find params[:id]
  end

  def edit
    @meal = Meal.find params[:id]
  end

  def update
    meal_time = DateTime.parse(meal_params[:meal_date] + ' ' + meal_params[:meal_time])

    meal = Meal.find params[:id]
    meal.update({
      user_id: meal_params[:user_id],
      total_carbs: meal_params[:total_carbs],
      meal_time: meal_time
    })
    redirect_to meal_path
  end

  def destroy
    meal = Meal.find params[:id]
    meal.destroy
    redirect_to meals_path
  end

  private
  def meal_params
    params.require(:meal).permit(:meal_time, :meal_date, :user_id, :total_carbs)
  end

  def check_if_logged_in
    redirect_to(root_path) unless @current_user.present?
  end

end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_form.html.erb
<div class="row">
  <div class="col-md-3">
    <%= form_for @meal do |f| %>
    <p>
      <%= f.label :meal_date, :title => "Select the day on which this meal was consumed." %>
      <%= f.date_field :meal_date, :class => "form-control", :required => true, :title => "Select the day on which this meal was consumed." %>
    </p>

    <p>
      <%= f.label :meal_time, :title => 'Enter the time at which this meal was consumed.' %>
      <%= f.time_field :meal_time, :class => "form-control", :required => true, :title => 'Enter the time at which this meal was consumed.' %>
    </p>

    <div class="text-right">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/meals/edit.html.erb
<h2>Edit meal - <%= @meal.meal_time.strftime('%e %B %Y, %R') %></h2>
<p>Edit time and date of this meal below</p>
<%= render :partial => 'form' %>

app/views/meals/index.html.erb
<h2><%= @current_user.username %>'s meals:</h2>

<% unless @current_user.meals.length == 0 %>
<ol>
  <% @meals.each do |meal| %>
    <li data-mealid="<%= meal.id %>"><%= link_to (meal.meal_time.strftime('%R, %e %B %Y')), meal_path(meal) %> <span class="badge"> Carbs: <%= meal.total_carbs %> </span> <a href="<%= edit_meal_path(meal.id) %>"><span class="fa fa-pencil"></span></a> <%= link_to "<span class='fa fa-trash-o'></span>".html_safe, meal_path(meal.id), :method => 'delete' %>
    </li>
  <% end %>
</ol>
<% else %>
  <p>You don't have any stored meals!</p><bk>
  <p>Click the button below to add a meal.</p>
<% end %>
<%= link_to 'Add New Meal', new_meal_path, :class => 'btn btn-primary' %>

app/views/meals/new.html.erb
<h3>New Meal</h3>
<%= render :partial => 'form' %>

app/views/meals/show.html.erb
<!-- DON'T MESS WITH ANY OF THIS! The span indentation, or lack of, is crucial to how the JS works as putting erb tags on a new line within a span adds spaces to the element -->

<h3>Here's your meal from <%= @meal.meal_time.strftime('%I:%M %P, %e %B %Y') %></h3>

<div class="row">
  <div class="col-md-12">
    <div class="alert alert-info" role="alert">In the Glucosy Calculator, an exchange is the quantity of food that contains approximately 15g of carbohydrates.
    <p>Search for a food below, read the nutritional information and add your prescribed insulation exchange ratio. Glucosy will provide the Calculated Insulin Dosage.</p></div>
  </div>
</div>

<div class="row">

  <div class="col-md-4">
    <div id="construct-meal-forms" class="hide-meal-construction">
      <h3>Construct Meal</h3>
      <div id="search-div">
        <form class="form-inline">
          <input type="text" id="query" placeholder="Enter a food" class="form-control">
          <a id="search" class="btn btn-default">Search</a>
        </form>
      </div>

      <div id="results-div">
        <ul id="search-results"></ul>
      </div>

      <div id="ajax-form">
        <form>
          <label for="form-foodname">Name of food</label>
          <input type="text" id="form-foodname" name="form-foodname" class="form-control" readonly="readonly">

          <label for="form-quantity">Quantity</label>
          <input type="number" id="form-quantity" name="form-quantity" class="form-control" min="0.1" step="0.1">

          <label for="form-serving-size-qty">Serving size qty</label>
          <input type="text" id="form-serving-size-qty" name="form-serving-size-qty" class="form-control" readonly="readonly">

          <label for="form-serving-size-unit">Serving size unit</label>
          <input type="text" id="form-serving-size-unit" name="form-serving-size-unit" class="form-control" readonly="readonly">

          <label for="form-serving-size-weight">Serving size weight</label>
          <input type="text" id="form-serving-size-weight" name="form-serving-size-weight" class="form-control" readonly="readonly">

          <label for="form-carbs">Carbs</label>
          <input type="text" id="form-carbs" name="form-carbs" class="form-control">

          <input type="hidden" name="form-meal-id" id="form-meal-id" value="<%= @meal.id %>">
          <br>
          <button id="form-submit" class="btn btn-primary">Add to meal</button>
          <a href="/meals" class="btn btn-success">Complete meal</a>
        </form>

      </div>
    </div>

    <div id="add-foods-to-meal">
      <br>
      <button class="btn btn-success btn-md" id="add-foods-to-meal-button">Add foods to meal</button>
    </div>
  </div>

  <div class="col-md-7 col-md-offset-1">
    <h4>You've added these foods to your meal:</h4>

    <!-- Throws up a list when the page loads. List is then manipulated by JS -->
    <ul id="added-foods">
      <% @meal.foods.each do |food| %>

        <li class="ruby-foods" data-food-id="<%= food.id %>" data-meal-id="<%= food.meal_id %>" data-carbs="<%= food.carbs %>" data-quantity="<%= food.quantity %>">
          <span class="badge food-badge">Qty: <%= food.quantity.to_i %></span><span class="badge food-badge">Carbs: <%= (food.total_carbs).round %></span><%= food.foodname %><span class="fa fa-trash-o ruby-delete"></span>
        </li>

      <% end %>
    </ul>

    <!-- Updated in foods.js as foods are added/deleted from list -->
    <span class="badge meal-carbs-badge" id="total-carbs">Total Carbs: <% sum = 0 %><% @meal.foods.each_with_index do |v, i| %><% sum += (@meal.foods[i].total_carbs) %><% end %><%= sum.round %>
    </span>
    <span class="badge meal-insulin-badge" id="insulin-required" data-bolus-insulin="<%= @current_user.bolus_insulin %>">Required Insulin Dose:
    <%= ((sum / 15) * @current_user.bolus_insulin).round(1) %>
    </span>
  </div>

</div>