config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#index'

  # get '/index' => 'pages#index'
  # OPEN SINGLE CALC PAGE
  get '/singlecalculation' => 'pages#calc'
  get '/weather' => 'pages#weather'  

  resources :users, :activities

  resources :meals do
    resources :foods
  end

  resources :bloodsugars, only: [:index] do
    collection { post :import }
  end

  # JSON ROUTES
  get '/dashboard' => 'users#dashboard'

  # BLOODSUGAR DATA JSON PAGE
  get '/readingdata' => 'bloodsugars#data'
  get '/readingdata/bslevel' => 'users#bslevel'
  get '/readingdata' => 'bloodsugars#data'
  get '/readingdata/readingtime' => 'users#readingtime'
  get '/readingdata/bslevel_lastthirty' => 'users#bslevel_lastthirty'
  get '/readingdata/readingtime_lastthirty' => 'users#readingtime_lastthirty'
  # MEAL DATA JSON PAGE
  get '/readingdata/foods' => 'foods#index'
  get '/readingdata/carbs' => 'foods#carbs'
  get '/readingdata/mealtime' => 'foods#mealtime'
  get '/readingdata/carbs_lastthirty' => 'foods#carbs_lastthirty'
  get '/readingdata/mealtime_lastthirty' => 'foods#mealtime_lastthirty'
  # ACTIVITY DATA JSON PAGE
  get '/readingdata/duration' => 'activities#duration'
  get '/readingdata/activity_time' => 'activities#activity_time'
  get '/readingdata/duration_lastthirty' => 'activities#duration_lastthirty'
  get '/readingdata/activity_time_lastthirty' => 'activities#activity_time_lastthirty'

  # SESSION LOGIN PAGE
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'


end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id            :integer          not null, primary key
#  activityname  :string
#  duration      :float
#  intensity     :integer
#  activity_time :datetime
#  created_at    :datetime
#  updated_at    :datetime
#  user_id       :integer
#  activity_date :datetime
#

class Activity < ActiveRecord::Base
  belongs_to :user
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
    
    before_action :check_if_logged_in, :only => [:index]

    def index
        @activities = Activity.all
    end

    def new
        @activity = Activity.new
    end

    def create
        activity_time = DateTime.parse(activity_params[:activity_date] + ' ' + activity_params[:activity_time])

        activity = @current_user.activities.create({
            user_id: @current_user.id,
            activityname: activity_params[:activityname],
            duration: activity_params[:duration],
            intensity: activity_params[:intensity],
            activity_time: activity_time
        })
        redirect_to activity
    end

    def show
        @activity = Activity.find params[:id]
    end

    def edit
        @activity = Activity.find params[:id]
    end

    def update
        activity = Activity.find params[:id]
        activity.update activity_params
        redirect_to activity
    end

    def destroy
        activity = Activity.find params[:id]
        activity.destroy
        redirect_to activities_path
    end

    # ACTIVITY CHART ACTIONS
    def duration
        activity = Activity.pluck :duration
        render :json => activity
    end

    def activity_time
        activity_time = Activity.pluck :activity_time
        render :json => activity_time
    end

    def duration_lastthirty
        activities = Activity.where(:user_id => @current_user.id).limit(30).pluck(:duration)
        render :json => activities  
    end

    def activity_time_lastthirty
        activity_timeStrf =[]
        activity_time = Activity.where(:user_id => @current_user.id).limit(30).pluck(:activity_time)
            activity_time.each do |time|
                activity_timeStrf<< time.strftime("%R, %d/%m")
            end
        render :json => activity_timeStrf
    end

    private
    def activity_params
        params.require(:activity).permit(:user_id, :activityname, :duration, :intensity, :activity_time, :activity_date)
    end

    def check_if_logged_in
        redirect_to(root_path) unless @current_user.present?
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for @activity do |f| %>
    <div class="form-group">
    <%= f.label :activityname, "Activity name", :title => 'Describe the type of activity that you completed.' %>
    <%= f.text_field :activityname, :autofocus => true, :required => true, :title => 'Describe the type of activity that you completed.', :class => 'form-control', :placeholder => 'eg. 5k run'  %>
    </div>
    <div class="form-group">
    <%= f.label :duration, "Duration (mins)", :title => 'How many minutes did you do this for?' %>
    <%= f.number_field :duration, :title => 'How many minutes did you do this for?', :class => 'form-control'  %>
    </div>
    <div class="form-group">
    <%= f.label :intensity, "Intensity (1-10)", :title => "On a scale of 1 to 10, how intense was this activity? For example, a casual walk would be 1 or 2. However, a sprint session where you achieve > 80% of your maximum heart rate would be around 8-10" %>
    <%= f.number_field :intensity, :min => '1', :max => '10', :title => "On a scale of 1 to 10, how intense was this activity? For example, a casual walk would be 1 or 2. However, a sprint session where you achieve > 80% of your maximum heart rate would be around 8-10", :class => 'form-control', :placeholder => '1 (Very Light) - 10 (Maximal exertion)'  %>
    </div>
    <div class="form-group">
    <%= f.label :activity_date, "Date of activity", :title => 'When did you do this activity?' %>
    <%= f.date_field :activity_date, :title => 'When did you do this activity?', :class => 'form-control'  %>
    </div>
    <div class="form-group">
    <%= f.label :activity_time, "Activity end time", :title => 'What time did you finish this activity?' %>
    <%= f.time_field :activity_time, :title => 'What time did you finish this activity?', :class => 'form-control'  %>
    </div>
    <div class="text-right">
    <%= f.submit :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/activities/edit.html.erb
<h2>Edit Food</h2>
<%= render :partial => 'form' %>

app/views/activities/index.html.erb
<h2>Activities Index</h2>

<ol>
    <% @activities.each do |activity| %>
        <li><%= link_to activity.activityname, activity_path(activity) %>: <%= activity.activity_time.strftime('%e %B %Y, %R') %> <span class="badge">Intensity: <%= activity.intensity %></span> <a href="<%= edit_activity_path(activity.id) %>"><span class="fa fa-pencil"></span></a> <%= link_to "<span class='fa fa-trash-o'></span>".html_safe, activity_path(activity.id), :method => 'delete' %></li>
    <% end %>
</ol>

<%= link_to 'Add New Activity', new_activity_path, :class => 'btn btn-primary' %>

app/views/activities/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h2>Create Activity</h2>
      <%= render :partial => 'form' %>
    </div>
  </div>
</div>

app/views/activities/show.html.erb
<h2><%= @activity.activityname %> - <%= @activity.activity_time.strftime('%e %B %Y, %R') %></h2>

<ul class="list-group">
  <li class="list-group-item">
    <strong>Duration:</strong> <%= @activity.duration.to_i %> minutes
  </li>
    <li class="list-group-item">
    <strong>Intensity:</strong> <%= @activity.intensity %> out of 10
  </li>
</ul>

<%= link_to 'Back', activities_path %>

<div class="text-right">
  <%= link_to 'Delete activity', activity_path, :method => 'delete', :data => {:confirm => 'Are you sure?'} %>
  <%= link_to 'Edit activity', edit_activity_path %>
</div>